// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWhVcd5HAIRsskwZ-_j3av7wxDViKgFkI',
    appId: '1:782034435679:web:3cc6d58bc663b26a9aa5ea',
    messagingSenderId: '782034435679',
    projectId: 'smart-boba',
    authDomain: 'smart-boba.firebaseapp.com',
    storageBucket: 'smart-boba.firebasestorage.app',
    measurementId: 'G-9B9H45S902',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-yalpbdNkZz9j2fROW30jWAWr4E3V9Xo',
    appId: '1:782034435679:android:f8cf546f7248bf3f9aa5ea',
    messagingSenderId: '782034435679',
    projectId: 'smart-boba',
    storageBucket: 'smart-boba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9KKO3_ISuK-OiWahk8nfH9rZDGTIvZF4',
    appId: '1:782034435679:ios:351bea3bc16cb4c39aa5ea',
    messagingSenderId: '782034435679',
    projectId: 'smart-boba',
    storageBucket: 'smart-boba.firebasestorage.app',
    iosBundleId: 'com.example.smartBoba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9KKO3_ISuK-OiWahk8nfH9rZDGTIvZF4',
    appId: '1:782034435679:ios:351bea3bc16cb4c39aa5ea',
    messagingSenderId: '782034435679',
    projectId: 'smart-boba',
    storageBucket: 'smart-boba.firebasestorage.app',
    iosBundleId: 'com.example.smartBoba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWhVcd5HAIRsskwZ-_j3av7wxDViKgFkI',
    appId: '1:782034435679:web:6d2af3e129ee4f839aa5ea',
    messagingSenderId: '782034435679',
    projectId: 'smart-boba',
    authDomain: 'smart-boba.firebaseapp.com',
    storageBucket: 'smart-boba.firebasestorage.app',
    measurementId: 'G-JHHSELWPWV',
  );
}
